-- Worldwide master reference data.
--
-- Idempotent by design: every statement is ON CONFLICT DO NOTHING keyed on the
-- natural unique column, so re-running changes nothing and any row the user has
-- already edited keeps their version. Nothing here is ever updated or deleted.
--
-- Sources: ISO 3166-1 (countries), ISO 4217 (currencies), UN/LOCODE (ports),
-- Incoterms 2020. Port codes were validated against the official UN/LOCODE code
-- list; names use its spelling.

-- 250 countries (ISO 3166-1 alpha-2)
INSERT INTO countries (id, code, name, region, is_active, created_at, updated_at) VALUES
  (gen_random_uuid()::text, 'AD', 'Andorra', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'AE', 'United Arab Emirates', 'Asia', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'AF', 'Afghanistan', 'Asia', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'AG', 'Antigua and Barbuda', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'AI', 'Anguilla', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'AL', 'Albania', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'AM', 'Armenia', 'Asia', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'AO', 'Angola', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'AQ', 'Antarctica', 'Antarctic', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'AR', 'Argentina', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'AS', 'American Samoa', 'Oceania', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'AT', 'Austria', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'AU', 'Australia', 'Oceania', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'AW', 'Aruba', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'AX', 'Åland Islands', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'AZ', 'Azerbaijan', 'Asia', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'BA', 'Bosnia and Herzegovina', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'BB', 'Barbados', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'BD', 'Bangladesh', 'Asia', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'BE', 'Belgium', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'BF', 'Burkina Faso', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'BG', 'Bulgaria', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'BH', 'Bahrain', 'Asia', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'BI', 'Burundi', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'BJ', 'Benin', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'BL', 'Saint Barthélemy', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'BM', 'Bermuda', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'BN', 'Brunei', 'Asia', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'BO', 'Bolivia', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'BQ', 'Caribbean Netherlands', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'BR', 'Brazil', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'BS', 'Bahamas', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'BT', 'Bhutan', 'Asia', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'BV', 'Bouvet Island', 'Antarctic', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'BW', 'Botswana', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'BY', 'Belarus', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'BZ', 'Belize', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'CA', 'Canada', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'CC', 'Cocos (Keeling) Islands', 'Oceania', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'CD', 'DR Congo', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'CF', 'Central African Republic', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'CG', 'Republic of the Congo', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'CH', 'Switzerland', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'CI', 'Ivory Coast', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'CK', 'Cook Islands', 'Oceania', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'CL', 'Chile', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'CM', 'Cameroon', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'CN', 'China', 'Asia', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'CO', 'Colombia', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'CR', 'Costa Rica', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'CU', 'Cuba', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'CV', 'Cape Verde', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'CW', 'Curaçao', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'CX', 'Christmas Island', 'Oceania', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'CY', 'Cyprus', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'CZ', 'Czechia', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'DE', 'Germany', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'DJ', 'Djibouti', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'DK', 'Denmark', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'DM', 'Dominica', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'DO', 'Dominican Republic', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'DZ', 'Algeria', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'EC', 'Ecuador', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'EE', 'Estonia', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'EG', 'Egypt', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'EH', 'Western Sahara', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'ER', 'Eritrea', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'ES', 'Spain', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'ET', 'Ethiopia', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'FI', 'Finland', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'FJ', 'Fiji', 'Oceania', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'FK', 'Falkland Islands', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'FM', 'Micronesia', 'Oceania', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'FO', 'Faroe Islands', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'FR', 'France', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'GA', 'Gabon', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'GB', 'United Kingdom', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'GD', 'Grenada', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'GE', 'Georgia', 'Asia', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'GF', 'French Guiana', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'GG', 'Guernsey', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'GH', 'Ghana', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'GI', 'Gibraltar', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'GL', 'Greenland', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'GM', 'Gambia', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'GN', 'Guinea', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'GP', 'Guadeloupe', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'GQ', 'Equatorial Guinea', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'GR', 'Greece', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'GS', 'South Georgia', 'Antarctic', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'GT', 'Guatemala', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'GU', 'Guam', 'Oceania', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'GW', 'Guinea-Bissau', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'GY', 'Guyana', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'HK', 'Hong Kong', 'Asia', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'HM', 'Heard Island and McDonald Islands', 'Antarctic', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'HN', 'Honduras', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'HR', 'Croatia', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'HT', 'Haiti', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'HU', 'Hungary', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'ID', 'Indonesia', 'Asia', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'IE', 'Ireland', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'IL', 'Israel', 'Asia', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'IM', 'Isle of Man', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'IN', 'India', 'Asia', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'IO', 'British Indian Ocean Territory', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'IQ', 'Iraq', 'Asia', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'IR', 'Iran', 'Asia', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'IS', 'Iceland', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'IT', 'Italy', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'JE', 'Jersey', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'JM', 'Jamaica', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'JO', 'Jordan', 'Asia', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'JP', 'Japan', 'Asia', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'KE', 'Kenya', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'KG', 'Kyrgyzstan', 'Asia', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'KH', 'Cambodia', 'Asia', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'KI', 'Kiribati', 'Oceania', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'KM', 'Comoros', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'KN', 'Saint Kitts and Nevis', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'KP', 'North Korea', 'Asia', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'KR', 'South Korea', 'Asia', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'KW', 'Kuwait', 'Asia', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'KY', 'Cayman Islands', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'KZ', 'Kazakhstan', 'Asia', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'LA', 'Laos', 'Asia', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'LB', 'Lebanon', 'Asia', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'LC', 'Saint Lucia', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'LI', 'Liechtenstein', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'LK', 'Sri Lanka', 'Asia', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'LR', 'Liberia', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'LS', 'Lesotho', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'LT', 'Lithuania', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'LU', 'Luxembourg', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'LV', 'Latvia', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'LY', 'Libya', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'MA', 'Morocco', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'MC', 'Monaco', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'MD', 'Moldova', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'ME', 'Montenegro', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'MF', 'Saint Martin', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'MG', 'Madagascar', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'MH', 'Marshall Islands', 'Oceania', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'MK', 'North Macedonia', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'ML', 'Mali', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'MM', 'Myanmar', 'Asia', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'MN', 'Mongolia', 'Asia', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'MO', 'Macau', 'Asia', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'MP', 'Northern Mariana Islands', 'Oceania', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'MQ', 'Martinique', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'MR', 'Mauritania', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'MS', 'Montserrat', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'MT', 'Malta', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'MU', 'Mauritius', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'MV', 'Maldives', 'Asia', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'MW', 'Malawi', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'MX', 'Mexico', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'MY', 'Malaysia', 'Asia', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'MZ', 'Mozambique', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'NA', 'Namibia', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'NC', 'New Caledonia', 'Oceania', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'NE', 'Niger', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'NF', 'Norfolk Island', 'Oceania', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'NG', 'Nigeria', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'NI', 'Nicaragua', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'NL', 'Netherlands', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'NO', 'Norway', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'NP', 'Nepal', 'Asia', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'NR', 'Nauru', 'Oceania', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'NU', 'Niue', 'Oceania', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'NZ', 'New Zealand', 'Oceania', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'OM', 'Oman', 'Asia', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'PA', 'Panama', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'PE', 'Peru', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'PF', 'French Polynesia', 'Oceania', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'PG', 'Papua New Guinea', 'Oceania', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'PH', 'Philippines', 'Asia', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'PK', 'Pakistan', 'Asia', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'PL', 'Poland', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'PM', 'Saint Pierre and Miquelon', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'PN', 'Pitcairn Islands', 'Oceania', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'PR', 'Puerto Rico', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'PS', 'Palestine', 'Asia', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'PT', 'Portugal', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'PW', 'Palau', 'Oceania', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'PY', 'Paraguay', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'QA', 'Qatar', 'Asia', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'RE', 'Réunion', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'RO', 'Romania', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'RS', 'Serbia', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'RU', 'Russia', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'RW', 'Rwanda', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'SA', 'Saudi Arabia', 'Asia', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'SB', 'Solomon Islands', 'Oceania', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'SC', 'Seychelles', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'SD', 'Sudan', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'SE', 'Sweden', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'SG', 'Singapore', 'Asia', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'SH', 'Saint Helena, Ascension and Tristan da Cunha', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'SI', 'Slovenia', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'SJ', 'Svalbard and Jan Mayen', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'SK', 'Slovakia', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'SL', 'Sierra Leone', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'SM', 'San Marino', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'SN', 'Senegal', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'SO', 'Somalia', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'SR', 'Suriname', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'SS', 'South Sudan', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'ST', 'São Tomé and Príncipe', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'SV', 'El Salvador', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'SX', 'Sint Maarten', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'SY', 'Syria', 'Asia', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'SZ', 'Eswatini', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'TC', 'Turks and Caicos Islands', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'TD', 'Chad', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'TF', 'French Southern and Antarctic Lands', 'Antarctic', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'TG', 'Togo', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'TH', 'Thailand', 'Asia', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'TJ', 'Tajikistan', 'Asia', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'TK', 'Tokelau', 'Oceania', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'TL', 'Timor-Leste', 'Asia', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'TM', 'Turkmenistan', 'Asia', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'TN', 'Tunisia', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'TO', 'Tonga', 'Oceania', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'TR', 'Türkiye', 'Asia', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'TT', 'Trinidad and Tobago', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'TV', 'Tuvalu', 'Oceania', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'TW', 'Taiwan', 'Asia', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'TZ', 'Tanzania', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'UA', 'Ukraine', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'UG', 'Uganda', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'UM', 'United States Minor Outlying Islands', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'US', 'United States', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'UY', 'Uruguay', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'UZ', 'Uzbekistan', 'Asia', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'VA', 'Vatican City', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'VC', 'Saint Vincent and the Grenadines', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'VE', 'Venezuela', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'VG', 'British Virgin Islands', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'VI', 'United States Virgin Islands', 'Americas', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'VN', 'Vietnam', 'Asia', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'VU', 'Vanuatu', 'Oceania', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'WF', 'Wallis and Futuna', 'Oceania', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'WS', 'Samoa', 'Oceania', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'XK', 'Kosovo', 'Europe', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'YE', 'Yemen', 'Asia', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'YT', 'Mayotte', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'ZA', 'South Africa', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'ZM', 'Zambia', 'Africa', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'ZW', 'Zimbabwe', 'Africa', true, NOW(), NOW())
ON CONFLICT (code) DO NOTHING;

-- 179 currencies (ISO 4217, symbols from CLDR)
INSERT INTO currencies (id, code, name, symbol, is_active, created_at, updated_at) VALUES
  (gen_random_uuid()::text, 'AED', 'UAE Dirham', 'AED', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'AFN', 'Afghani', 'AFN', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'ALL', 'Lek', 'ALL', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'AMD', 'Armenian Dram', 'AMD', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'ANG', 'Netherlands Antillean Guilder', 'ANG', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'AOA', 'Kwanza', 'AOA', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'ARS', 'Argentine Peso', 'ARS', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'AUD', 'Australian Dollar', 'A$', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'AWG', 'Aruban Florin', 'AWG', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'AZN', 'Azerbaijan Manat', 'AZN', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'BAM', 'Convertible Mark', 'BAM', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'BBD', 'Barbados Dollar', 'BBD', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'BDT', 'Taka', 'BDT', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'BGN', 'Bulgarian Lev', 'BGN', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'BHD', 'Bahraini Dinar', 'BHD', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'BIF', 'Burundi Franc', 'BIF', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'BMD', 'Bermudian Dollar', 'BMD', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'BND', 'Brunei Dollar', 'BND', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'BOB', 'Boliviano', 'BOB', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'BOV', 'Mvdol', 'BOV', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'BRL', 'Brazilian Real', 'R$', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'BSD', 'Bahamian Dollar', 'BSD', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'BTN', 'Ngultrum', 'BTN', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'BWP', 'Pula', 'BWP', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'BYN', 'Belarusian Ruble', 'BYN', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'BZD', 'Belize Dollar', 'BZD', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'CAD', 'Canadian Dollar', 'CA$', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'CDF', 'Congolese Franc', 'CDF', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'CHE', 'WIR Euro', 'CHE', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'CHF', 'Swiss Franc', 'CHF', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'CHW', 'WIR Franc', 'CHW', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'CLF', 'Unidad de Fomento', 'CLF', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'CLP', 'Chilean Peso', 'CLP', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'CNY', 'Yuan Renminbi', 'CN¥', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'COP', 'Colombian Peso', 'COP', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'COU', 'Unidad de Valor Real', 'COU', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'CRC', 'Costa Rican Colon', 'CRC', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'CUC', 'Peso Convertible', 'CUC', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'CUP', 'Cuban Peso', 'CUP', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'CVE', 'Cabo Verde Escudo', 'CVE', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'CZK', 'Czech Koruna', 'CZK', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'DJF', 'Djibouti Franc', 'DJF', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'DKK', 'Danish Krone', 'DKK', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'DOP', 'Dominican Peso', 'DOP', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'DZD', 'Algerian Dinar', 'DZD', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'EGP', 'Egyptian Pound', 'EGP', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'ERN', 'Nakfa', 'ERN', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'ETB', 'Ethiopian Birr', 'ETB', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'EUR', 'Euro', '€', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'FJD', 'Fiji Dollar', 'FJD', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'FKP', 'Falkland Islands Pound', 'FKP', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'GBP', 'Pound Sterling', '£', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'GEL', 'Lari', 'GEL', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'GHS', 'Ghana Cedi', 'GHS', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'GIP', 'Gibraltar Pound', 'GIP', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'GMD', 'Dalasi', 'GMD', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'GNF', 'Guinean Franc', 'GNF', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'GTQ', 'Quetzal', 'GTQ', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'GYD', 'Guyana Dollar', 'GYD', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'HKD', 'Hong Kong Dollar', 'HK$', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'HNL', 'Lempira', 'HNL', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'HTG', 'Gourde', 'HTG', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'HUF', 'Forint', 'HUF', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'IDR', 'Rupiah', 'IDR', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'ILS', 'New Israeli Sheqel', '₪', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'INR', 'Indian Rupee', '₹', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'IQD', 'Iraqi Dinar', 'IQD', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'IRR', 'Iranian Rial', 'IRR', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'ISK', 'Iceland Krona', 'ISK', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'JMD', 'Jamaican Dollar', 'JMD', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'JOD', 'Jordanian Dinar', 'JOD', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'JPY', 'Yen', '¥', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'KES', 'Kenyan Shilling', 'KES', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'KGS', 'Som', 'KGS', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'KHR', 'Riel', 'KHR', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'KMF', 'Comorian Franc ', 'KMF', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'KPW', 'North Korean Won', 'KPW', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'KRW', 'Won', '₩', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'KWD', 'Kuwaiti Dinar', 'KWD', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'KYD', 'Cayman Islands Dollar', 'KYD', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'KZT', 'Tenge', 'KZT', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'LAK', 'Lao Kip', 'LAK', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'LBP', 'Lebanese Pound', 'LBP', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'LKR', 'Sri Lanka Rupee', 'LKR', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'LRD', 'Liberian Dollar', 'LRD', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'LSL', 'Loti', 'LSL', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'LYD', 'Libyan Dinar', 'LYD', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'MAD', 'Moroccan Dirham', 'MAD', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'MDL', 'Moldovan Leu', 'MDL', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'MGA', 'Malagasy Ariary', 'MGA', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'MKD', 'Denar', 'MKD', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'MMK', 'Kyat', 'MMK', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'MNT', 'Tugrik', 'MNT', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'MOP', 'Pataca', 'MOP', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'MRU', 'Ouguiya', 'MRU', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'MUR', 'Mauritius Rupee', 'MUR', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'MVR', 'Rufiyaa', 'MVR', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'MWK', 'Malawi Kwacha', 'MWK', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'MXN', 'Mexican Peso', 'MX$', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'MXV', 'Mexican Unidad de Inversion (UDI)', 'MXV', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'MYR', 'Malaysian Ringgit', 'MYR', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'MZN', 'Mozambique Metical', 'MZN', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'NAD', 'Namibia Dollar', 'NAD', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'NGN', 'Naira', 'NGN', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'NIO', 'Cordoba Oro', 'NIO', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'NOK', 'Norwegian Krone', 'NOK', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'NPR', 'Nepalese Rupee', 'NPR', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'NZD', 'New Zealand Dollar', 'NZ$', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'OMR', 'Rial Omani', 'OMR', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'PAB', 'Balboa', 'PAB', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'PEN', 'Sol', 'PEN', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'PGK', 'Kina', 'PGK', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'PHP', 'Philippine Peso', '₱', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'PKR', 'Pakistan Rupee', 'PKR', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'PLN', 'Zloty', 'PLN', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'PYG', 'Guarani', 'PYG', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'QAR', 'Qatari Rial', 'QAR', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'RON', 'Romanian Leu', 'RON', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'RSD', 'Serbian Dinar', 'RSD', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'RUB', 'Russian Ruble', 'RUB', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'RWF', 'Rwanda Franc', 'RWF', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'SAR', 'Saudi Riyal', 'SAR', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'SBD', 'Solomon Islands Dollar', 'SBD', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'SCR', 'Seychelles Rupee', 'SCR', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'SDG', 'Sudanese Pound', 'SDG', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'SEK', 'Swedish Krona', 'SEK', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'SGD', 'Singapore Dollar', 'SGD', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'SHP', 'Saint Helena Pound', 'SHP', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'SLE', 'Leone', 'SLE', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'SOS', 'Somali Shilling', 'SOS', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'SRD', 'Surinam Dollar', 'SRD', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'SSP', 'South Sudanese Pound', 'SSP', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'STN', 'Dobra', 'STN', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'SVC', 'El Salvador Colon', 'SVC', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'SYP', 'Syrian Pound', 'SYP', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'SZL', 'Lilangeni', 'SZL', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'THB', 'Baht', 'THB', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'TJS', 'Somoni', 'TJS', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'TMT', 'Turkmenistan New Manat', 'TMT', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'TND', 'Tunisian Dinar', 'TND', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'TOP', 'Pa’anga', 'TOP', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'TRY', 'Turkish Lira', 'TRY', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'TTD', 'Trinidad and Tobago Dollar', 'TTD', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'TWD', 'New Taiwan Dollar', 'NT$', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'TZS', 'Tanzanian Shilling', 'TZS', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'UAH', 'Hryvnia', 'UAH', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'UGX', 'Uganda Shilling', 'UGX', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'USD', 'US Dollar', '$', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'USN', 'US Dollar (Next day)', 'USN', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'UYI', 'Uruguay Peso en Unidades Indexadas (UI)', 'UYI', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'UYU', 'Peso Uruguayo', 'UYU', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'UYW', 'Unidad Previsional', 'UYW', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'UZS', 'Uzbekistan Sum', 'UZS', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'VED', 'Bolívar Soberano', 'VED', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'VES', 'Bolívar Soberano', 'VES', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'VND', 'Dong', '₫', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'VUV', 'Vatu', 'VUV', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'WST', 'Tala', 'WST', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'XAF', 'CFA Franc BEAC', 'FCFA', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'XAG', 'Silver', 'XAG', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'XAU', 'Gold', 'XAU', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'XBA', 'Bond Markets Unit European Composite Unit (EURCO)', 'XBA', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'XBB', 'Bond Markets Unit European Monetary Unit (E.M.U.-6)', 'XBB', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'XBC', 'Bond Markets Unit European Unit of Account 9 (E.U.A.-9)', 'XBC', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'XBD', 'Bond Markets Unit European Unit of Account 17 (E.U.A.-17)', 'XBD', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'XCD', 'East Caribbean Dollar', 'EC$', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'XDR', 'SDR (Special Drawing Right)', 'XDR', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'XOF', 'CFA Franc BCEAO', 'F CFA', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'XPD', 'Palladium', 'XPD', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'XPF', 'CFP Franc', 'CFPF', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'XPT', 'Platinum', 'XPT', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'XSU', 'Sucre', 'XSU', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'XTS', 'Codes specifically reserved for testing purposes', 'XTS', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'XUA', 'ADB Unit of Account', 'XUA', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'XXX', 'The codes assigned for transactions where no currency is involved', '¤', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'YER', 'Yemeni Rial', 'YER', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'ZAR', 'Rand', 'ZAR', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'ZMW', 'Zambian Kwacha', 'ZMW', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'ZWG', 'Zimbabwe Gold', 'ZWG', true, NOW(), NOW())
ON CONFLICT (code) DO NOTHING;

-- Incoterms 2020 (all eleven)
INSERT INTO incoterms (id, code, name, description, is_active, created_at, updated_at) VALUES
  (gen_random_uuid()::text, 'EXW', 'Ex Works', 'Seller makes goods available at their premises. Buyer bears all cost and risk from that point.', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'FCA', 'Free Carrier', 'Seller delivers to the carrier nominated by the buyer at a named place. Risk passes on delivery.', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'FAS', 'Free Alongside Ship', 'Seller delivers alongside the vessel at the named port of shipment. Sea and inland waterway only.', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'FOB', 'Free on Board', 'Seller delivers on board the vessel at the named port of shipment. Sea and inland waterway only.', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'CFR', 'Cost and Freight', 'Seller pays carriage to the named destination port. Risk passes when goods are on board.', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'CIF', 'Cost, Insurance and Freight', 'As CFR, and the seller also buys minimum cargo insurance. Sea and inland waterway only.', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'CPT', 'Carriage Paid To', 'Seller pays carriage to the named destination. Risk passes when goods are handed to the first carrier.', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'CIP', 'Carriage and Insurance Paid To', 'As CPT, and the seller also buys insurance at the higher all-risks level.', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'DAP', 'Delivered at Place', 'Seller delivers ready for unloading at the named destination and bears risk until then.', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'DPU', 'Delivered at Place Unloaded', 'Seller delivers and unloads at the named destination. Replaced DAT in Incoterms 2020.', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'DDP', 'Delivered Duty Paid', 'Seller delivers cleared for import, bearing duties and taxes at the destination.', true, NOW(), NOW())
ON CONFLICT (code) DO NOTHING;

-- Product categories relevant to Indian export trade
INSERT INTO product_categories (id, name, description, is_active, created_at, updated_at) VALUES
  (gen_random_uuid()::text, 'Spices', 'Whole and ground spices', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'Grains & Cereals', 'Rice, wheat, millets and other cereals', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'Pulses & Lentils', 'Dals, grams and other pulses', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'Oil Seeds', 'Sesame, groundnut, mustard and other oil seeds', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'Fresh Fruits & Vegetables', 'Perishable horticultural produce', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'Processed Foods', 'Packaged and value-added food products', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'Tea & Coffee', 'Bulk and packaged tea and coffee', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'Textiles & Garments', 'Fabrics, made-ups and ready-made garments', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'Handicrafts', 'Artisanal and decorative goods', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'Leather Goods', 'Finished leather and leather products', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'Chemicals', 'Industrial and speciality chemicals', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'Pharmaceuticals', 'Formulations and bulk drugs', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'Engineering Goods', 'Machinery, castings and fabricated metal', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'Gems & Jewellery', 'Cut stones and finished jewellery', true, NOW(), NOW()),
  (gen_random_uuid()::text, 'Herbal & Ayurvedic', 'Botanical extracts and traditional preparations', true, NOW(), NOW())
ON CONFLICT (name) DO NOTHING;

-- 426 ports and air-cargo gateways (UN/LOCODE).
-- country_id is resolved by subquery, so a port is only inserted once its
-- country row exists - which the statement above guarantees.
INSERT INTO ports (id, code, name, country_id, type, is_active, created_at, updated_at)
SELECT gen_random_uuid()::text, v.code, v.name, c.id, v.type, true, NOW(), NOW()
FROM (VALUES
  ('INNSA', 'Jawaharlal Nehru (Nhava Sheva)', 'IN', 'SEA'),
  ('INMUN', 'Mundra', 'IN', 'SEA'),
  ('INIXY', 'Kandla', 'IN', 'SEA'),
  ('INMAA', 'Chennai (ex Madras)', 'IN', 'SEA'),
  ('INENR', 'Ennore', 'IN', 'SEA'),
  ('INKTP', 'Kattupalli Port', 'IN', 'SEA'),
  ('INTUT', 'Tuticorin', 'IN', 'SEA'),
  ('INCOK', 'Kochi', 'IN', 'SEA'),
  ('INNML', 'New Mangalore', 'IN', 'SEA'),
  ('INMRM', 'Marmagao (Marmugao)', 'IN', 'SEA'),
  ('INVTZ', 'Visakhapatnam', 'IN', 'SEA'),
  ('INPPT', 'Paradip Port', 'IN', 'SEA'),
  ('INHAL', 'Haldia', 'IN', 'SEA'),
  ('INCCU', 'Kolkata (ex Calcutta)', 'IN', 'SEA'),
  ('INPAV', 'Pipavav (Victor) Port', 'IN', 'SEA'),
  ('INHZA', 'Hazira Port/Surat', 'IN', 'SEA'),
  ('INDAH', 'Dahej', 'IN', 'SEA'),
  ('INKRI', 'Krishnapatnam', 'IN', 'SEA'),
  ('INGGV', 'Gangavaram', 'IN', 'SEA'),
  ('INKAK', 'Kakinada', 'IN', 'SEA'),
  ('INBED', 'Bedi', 'IN', 'SEA'),
  ('INOKH', 'Okha', 'IN', 'SEA'),
  ('INPBD', 'Porbandar', 'IN', 'SEA'),
  ('INVVA', 'Veraval', 'IN', 'SEA'),
  ('INBHU', 'Bhavnagar', 'IN', 'SEA'),
  ('INJBD', 'Jafarabad', 'IN', 'SEA'),
  ('INTUN', 'Tuna', 'IN', 'SEA'),
  ('INVAD', 'Vadinar', 'IN', 'SEA'),
  ('INSIK', 'Sika', 'IN', 'SEA'),
  ('INMDA', 'Magdalla', 'IN', 'SEA'),
  ('INKRW', 'Karwar', 'IN', 'SEA'),
  ('INBEY', 'Beypore', 'IN', 'SEA'),
  ('INAZK', 'Azhikkal', 'IN', 'SEA'),
  ('INKRK', 'Karaikal', 'IN', 'SEA'),
  ('INNPT', 'Nagappattinam', 'IN', 'SEA'),
  ('INCDL', 'Cuddalore', 'IN', 'SEA'),
  ('INVZJ', 'Vazhinjam', 'IN', 'SEA'),
  ('INBOM', 'Mumbai (ex Bombay)', 'IN', 'SEA'),
  ('INDMQ', 'Dhamra Port', 'IN', 'SEA'),
  ('INGPR', 'Gopalpur', 'IN', 'SEA'),
  ('INMAC', 'Machilipatnam', 'IN', 'SEA'),
  ('INNEL', 'Nellore', 'IN', 'SEA'),
  ('INRVD', 'Revdanda', 'IN', 'SEA'),
  ('INALA', 'Alang SBY', 'IN', 'SEA'),
  ('INDHP', 'Dabhol Port', 'IN', 'SEA'),
  ('INKTW', 'Koheshwar', 'IN', 'SEA'),
  ('INMDV', 'Mandvi', 'IN', 'SEA'),
  ('INMGR', 'Mangrol', 'IN', 'SEA'),
  ('INNAV', 'Navlakhi', 'IN', 'SEA'),
  ('INPAN', 'Panaji Port', 'IN', 'SEA'),
  ('INPNM', 'Panambur, Va Mangalore', 'IN', 'SEA'),
  ('INSAL', 'Salaya', 'IN', 'SEA'),
  ('INTAD', 'Tadri', 'IN', 'SEA'),
  ('INUMB', 'Umbergoan', 'IN', 'SEA'),
  ('INURA', 'Uran', 'IN', 'SEA'),
  ('CNSGH', 'Shanghai', 'CN', 'SEA'),
  ('CNSNZ', 'Shenzhen', 'CN', 'SEA'),
  ('CNYTN', 'Yantian Pt', 'CN', 'SEA'),
  ('CNSHK', 'Shekou Pt', 'CN', 'SEA'),
  ('CNNBO', 'Ningbo', 'CN', 'SEA'),
  ('CNGGZ', 'Guangzhou', 'CN', 'SEA'),
  ('CNQIN', 'Qingdao', 'CN', 'SEA'),
  ('CNTNJ', 'Tianjin', 'CN', 'SEA'),
  ('CNTXG', 'Tianjin Xingang Pt', 'CN', 'SEA'),
  ('CNXAM', 'Xiamen', 'CN', 'SEA'),
  ('CNDAL', 'Dalian', 'CN', 'SEA'),
  ('CNLYG', 'Lianyungang', 'CN', 'SEA'),
  ('CNRZH', 'Rizhao', 'CN', 'SEA'),
  ('CNFZH', 'Fuzhou', 'CN', 'SEA'),
  ('CNSTG', 'Shantou', 'CN', 'SEA'),
  ('CNZNG', 'Zhanjiang Pt', 'CN', 'SEA'),
  ('CNHUA', 'Huangpu Pt', 'CN', 'SEA'),
  ('CNJIA', 'Jiangyin Pt', 'CN', 'SEA'),
  ('CNTAC', 'Taicang Pt', 'CN', 'SEA'),
  ('CNWEI', 'Weihai', 'CN', 'SEA'),
  ('CNYIK', 'Yinkou', 'CN', 'SEA'),
  ('CNZJG', 'Zhangjiagang', 'CN', 'SEA'),
  ('CNNTG', 'Nantong', 'CN', 'SEA'),
  ('CNSHP', 'Qinhuangdao Pt', 'CN', 'SEA'),
  ('HKHKG', 'Hong Kong', 'HK', 'SEA'),
  ('TWKHH', 'Kaohsiung', 'TW', 'SEA'),
  ('TWTXG', 'Taichung', 'TW', 'SEA'),
  ('TWKEL', 'Keelung (Chilung)', 'TW', 'SEA'),
  ('SGSIN', 'Singapore', 'SG', 'SEA'),
  ('KRPUS', 'Busan', 'KR', 'SEA'),
  ('KRINC', 'Incheon', 'KR', 'SEA'),
  ('KRKAN', 'Gwangyang', 'KR', 'SEA'),
  ('KRUSN', 'Ulsan', 'KR', 'SEA'),
  ('JPYOK', 'Yokohama', 'JP', 'SEA'),
  ('JPTYO', 'Tokyo', 'JP', 'SEA'),
  ('JPNGO', 'Nagoya, Aichi', 'JP', 'SEA'),
  ('JPUKB', 'Kobe', 'JP', 'SEA'),
  ('JPOSA', 'Osaka', 'JP', 'SEA'),
  ('JPTHS', 'Toyohashi', 'JP', 'SEA'),
  ('JPHKT', 'Hakata/Fukuoka', 'JP', 'SEA'),
  ('JPSMZ', 'Shimizu', 'JP', 'SEA'),
  ('JPMOJ', 'Moji/Kitakyushu', 'JP', 'SEA'),
  ('MYPKG', 'Port Klang (Pelabuhan Klang)', 'MY', 'SEA'),
  ('MYTPP', 'Tanjung Pelepas', 'MY', 'SEA'),
  ('MYPEN', 'Penang (Georgetown)', 'MY', 'SEA'),
  ('MYPGU', 'Pasir Gudang, Johor', 'MY', 'SEA'),
  ('MYBTU', 'Bintulu, Sarawak', 'MY', 'SEA'),
  ('MYKCH', 'Kuching, Sarawak', 'MY', 'SEA'),
  ('THLCH', 'Laem Chabang', 'TH', 'SEA'),
  ('THBKK', 'Bangkok', 'TH', 'SEA'),
  ('THSGK', 'Songkhla', 'TH', 'SEA'),
  ('VNSGN', 'Ho Chi Minh City', 'VN', 'SEA'),
  ('VNHPH', 'Haiphong', 'VN', 'SEA'),
  ('VNCMT', 'Cai Mep International Terminal', 'VN', 'SEA'),
  ('VNDAD', 'Da Nang', 'VN', 'SEA'),
  ('IDJKT', 'Jakarta, Java', 'ID', 'SEA'),
  ('IDSUB', 'Surabaya', 'ID', 'SEA'),
  ('IDSRG', 'Semarang', 'ID', 'SEA'),
  ('IDBLW', 'Belawan, Sumatra', 'ID', 'SEA'),
  ('IDPNK', 'Pontianak, Kalimantan', 'ID', 'SEA'),
  ('IDMAK', 'Makassar', 'ID', 'SEA'),
  ('PHMNL', 'Manila', 'PH', 'SEA'),
  ('PHCEB', 'Cebu', 'PH', 'SEA'),
  ('PHBTG', 'Batangas/Luzon', 'PH', 'SEA'),
  ('LKCMB', 'Colombo', 'LK', 'SEA'),
  ('LKHBA', 'Hambantota', 'LK', 'SEA'),
  ('BDCGP', 'Chattogram', 'BD', 'SEA'),
  ('BDMGL', 'Mongla', 'BD', 'SEA'),
  ('PKKHI', 'Karachi', 'PK', 'SEA'),
  ('PKQCT', 'Qasim International Container Terminal/Karachi', 'PK', 'SEA'),
  ('MMRGN', 'Yangon', 'MM', 'SEA'),
  ('KHKOS', 'Kampong Saom', 'KH', 'SEA'),
  ('AEJEA', 'Jebel Ali', 'AE', 'SEA'),
  ('AEDXB', 'Dubai', 'AE', 'SEA'),
  ('AEAUH', 'Abu Dhabi', 'AE', 'SEA'),
  ('AESHJ', 'Sharjah', 'AE', 'SEA'),
  ('AEKHL', 'Mina Khalifa/Abu Dhabi', 'AE', 'SEA'),
  ('AERKT', 'Ras al Khaimah', 'AE', 'SEA'),
  ('AEFJR', 'Al Fujayrah', 'AE', 'SEA'),
  ('OMSLL', 'Salalah', 'OM', 'SEA'),
  ('OMSOH', 'Sohar', 'OM', 'SEA'),
  ('OMMCT', 'Muscat', 'OM', 'SEA'),
  ('SAJED', 'Jeddah', 'SA', 'SEA'),
  ('SADMM', 'Ad Dammam', 'SA', 'SEA'),
  ('SAJUB', 'Jubail', 'SA', 'SEA'),
  ('SAYNB', 'Yanbu commercial city', 'SA', 'SEA'),
  ('QADOH', 'Doha', 'QA', 'SEA'),
  ('KWKWI', 'Kuwait', 'KW', 'SEA'),
  ('KWSAA', 'Shuaiba', 'KW', 'SEA'),
  ('BHKBS', 'Khalifa Bin Salman Port', 'BH', 'SEA'),
  ('BHMIN', 'Mina Sulman Port', 'BH', 'SEA'),
  ('IRBND', 'Bandar Abbas', 'IR', 'SEA'),
  ('IQUQR', 'Umm Qasr Port', 'IQ', 'SEA'),
  ('JOAQJ', 'Al ''Aqabah', 'JO', 'SEA'),
  ('YEADE', 'Aden', 'YE', 'SEA'),
  ('ILHFA', 'Haifa', 'IL', 'SEA'),
  ('ILASH', 'Ashdod', 'IL', 'SEA'),
  ('TRAMR', 'Ambarli', 'TR', 'SEA'),
  ('TRMER', 'Mersin', 'TR', 'SEA'),
  ('TRIZM', 'Izmir', 'TR', 'SEA'),
  ('TRIST', 'Istanbul', 'TR', 'SEA'),
  ('TRGEM', 'Gemlik', 'TR', 'SEA'),
  ('TRALI', 'Aliaga', 'TR', 'SEA'),
  ('NLRTM', 'Rotterdam', 'NL', 'SEA'),
  ('NLAMS', 'Amsterdam', 'NL', 'SEA'),
  ('BEANR', 'Antwerpen', 'BE', 'SEA'),
  ('BEZEE', 'Zeebrugge', 'BE', 'SEA'),
  ('DEHAM', 'Hamburg', 'DE', 'SEA'),
  ('DEBRV', 'Bremerhaven', 'DE', 'SEA'),
  ('DEWVN', 'Wilhelmshaven', 'DE', 'SEA'),
  ('DEBRE', 'Bremen', 'DE', 'SEA'),
  ('GBFXT', 'Felixstowe', 'GB', 'SEA'),
  ('GBSOU', 'Southampton', 'GB', 'SEA'),
  ('GBLGP', 'London Gateway Port', 'GB', 'SEA'),
  ('GBLIV', 'Liverpool', 'GB', 'SEA'),
  ('GBTIL', 'Tilbury', 'GB', 'SEA'),
  ('GBIMM', 'Immingham', 'GB', 'SEA'),
  ('FRLEH', 'Le Havre', 'FR', 'SEA'),
  ('FRFOS', 'Fos-sur-Mer', 'FR', 'SEA'),
  ('FRMRS', 'Marseille', 'FR', 'SEA'),
  ('FRDKK', 'Dunkerque', 'FR', 'SEA'),
  ('FRNTE', 'Nantes', 'FR', 'SEA'),
  ('ESVLC', 'Valencia', 'ES', 'SEA'),
  ('ESALG', 'Algeciras', 'ES', 'SEA'),
  ('ESBCN', 'Barcelona', 'ES', 'SEA'),
  ('ESBIO', 'Bilbao', 'ES', 'SEA'),
  ('ESLPA', 'Las Palmas de Gran Canaria', 'ES', 'SEA'),
  ('ESSVQ', 'Sevilla', 'ES', 'SEA'),
  ('ITGOA', 'Genova', 'IT', 'SEA'),
  ('ITSPE', 'La Spezia', 'IT', 'SEA'),
  ('ITGIT', 'Gioia Tauro', 'IT', 'SEA'),
  ('ITTRS', 'Trieste', 'IT', 'SEA'),
  ('ITLIV', 'Livorno', 'IT', 'SEA'),
  ('ITNAP', 'Napoli', 'IT', 'SEA'),
  ('ITVCE', 'Venezia', 'IT', 'SEA'),
  ('ITSAL', 'Salerno', 'IT', 'SEA'),
  ('PTLIS', 'Lisboa', 'PT', 'SEA'),
  ('PTLEI', 'Leixoes', 'PT', 'SEA'),
  ('PTSIE', 'Sines', 'PT', 'SEA'),
  ('GRPIR', 'Piraeus', 'GR', 'SEA'),
  ('GRSKG', 'Thessaloniki', 'GR', 'SEA'),
  ('MTMAR', 'Marsaxlokk', 'MT', 'SEA'),
  ('SIKOP', 'Koper', 'SI', 'SEA'),
  ('HRRJK', 'Rijeka', 'HR', 'SEA'),
  ('ROCND', 'Constanta', 'RO', 'SEA'),
  ('BGVAR', 'Varna', 'BG', 'SEA'),
  ('UAODS', 'Odesa', 'UA', 'SEA'),
  ('PLGDN', 'Gdansk', 'PL', 'SEA'),
  ('PLGDY', 'Gdynia', 'PL', 'SEA'),
  ('SEGOT', 'Goteborg', 'SE', 'SEA'),
  ('SEHEL', 'Helsingborg', 'SE', 'SEA'),
  ('DKAAR', 'Aarhus', 'DK', 'SEA'),
  ('DKCPH', 'Kobenhavn', 'DK', 'SEA'),
  ('NOOSL', 'Oslo', 'NO', 'SEA'),
  ('NOBGO', 'Bergen', 'NO', 'SEA'),
  ('FIHEL', 'Helsingfors (Helsinki)', 'FI', 'SEA'),
  ('FIKTK', 'Kotka', 'FI', 'SEA'),
  ('EETLL', 'Tallinn', 'EE', 'SEA'),
  ('LVRIX', 'Riga', 'LV', 'SEA'),
  ('LTKLJ', 'Klaipeda', 'LT', 'SEA'),
  ('RULED', 'Saint Petersburg (ex Leningrad)', 'RU', 'SEA'),
  ('RUNVS', 'Novorossiysk', 'RU', 'SEA'),
  ('RUVVO', 'Vladivostok', 'RU', 'SEA'),
  ('IEDUB', 'Dublin', 'IE', 'SEA'),
  ('IEORK', 'Cork', 'IE', 'SEA'),
  ('ISREY', 'Reykjavik', 'IS', 'SEA'),
  ('EGALY', 'El Iskandariya (Alexandria)', 'EG', 'SEA'),
  ('EGPSD', 'Port Said', 'EG', 'SEA'),
  ('EGPSE', 'Port Said East', 'EG', 'SEA'),
  ('EGDAM', 'Dumyat (Damietta)', 'EG', 'SEA'),
  ('EGSUZ', 'As Suways (Suez)', 'EG', 'SEA'),
  ('EGSOK', 'Sokhna Port', 'EG', 'SEA'),
  ('MAPTM', 'Tanger Med', 'MA', 'SEA'),
  ('MACAS', 'Casablanca', 'MA', 'SEA'),
  ('MAAGA', 'Agadir', 'MA', 'SEA'),
  ('TNTUN', 'Tunis', 'TN', 'SEA'),
  ('DZALG', 'Alger (Algiers)', 'DZ', 'SEA'),
  ('DZORN', 'Oran', 'DZ', 'SEA'),
  ('LYTIP', 'Tripoli', 'LY', 'SEA'),
  ('ZADUR', 'Durban', 'ZA', 'SEA'),
  ('ZACPT', 'Cape Town', 'ZA', 'SEA'),
  ('ZAPLZ', 'Gqeberha', 'ZA', 'SEA'),
  ('ZAELS', 'East London', 'ZA', 'SEA'),
  ('ZARCB', 'Richards Bay', 'ZA', 'SEA'),
  ('NGLOS', 'Lagos', 'NG', 'SEA'),
  ('NGAPP', 'Apapa', 'NG', 'SEA'),
  ('NGONN', 'Onne', 'NG', 'SEA'),
  ('NGTIN', 'Tincan/Lagos', 'NG', 'SEA'),
  ('GHTEM', 'Tema', 'GH', 'SEA'),
  ('GHTKD', 'Takoradi', 'GH', 'SEA'),
  ('CIABJ', 'Abidjan', 'CI', 'SEA'),
  ('SNDKR', 'Dakar', 'SN', 'SEA'),
  ('KEMBA', 'Mombasa', 'KE', 'SEA'),
  ('TZDAR', 'Dar es Salaam', 'TZ', 'SEA'),
  ('TZZNZ', 'Zanzibar', 'TZ', 'SEA'),
  ('DJJIB', 'Djibouti', 'DJ', 'SEA'),
  ('MZMPM', 'Maputo', 'MZ', 'SEA'),
  ('MZBEW', 'Beira', 'MZ', 'SEA'),
  ('AOLAD', 'Luanda', 'AO', 'SEA'),
  ('CMDLA', 'Douala', 'CM', 'SEA'),
  ('GALBV', 'Libreville', 'GA', 'SEA'),
  ('CGPNR', 'Pointe Noire', 'CG', 'SEA'),
  ('MUPLU', 'Port Louis', 'MU', 'SEA'),
  ('MGTMM', 'Tamatave (Toamasina)', 'MG', 'SEA'),
  ('SCPOV', 'Port Victoria', 'SC', 'SEA'),
  ('USLAX', 'Los Angeles', 'US', 'SEA'),
  ('USLGB', 'Long Beach', 'US', 'SEA'),
  ('USNYC', 'New York', 'US', 'SEA'),
  ('USSAV', 'Savannah', 'US', 'SEA'),
  ('USHOU', 'Houston', 'US', 'SEA'),
  ('USSEA', 'Seattle', 'US', 'SEA'),
  ('USTIW', 'Tacoma', 'US', 'SEA'),
  ('USORF', 'Norfolk', 'US', 'SEA'),
  ('USCHS', 'Charleston', 'US', 'SEA'),
  ('USOAK', 'Oakland', 'US', 'SEA'),
  ('USMIA', 'Miami', 'US', 'SEA'),
  ('USBAL', 'Baltimore', 'US', 'SEA'),
  ('USPHL', 'Philadelphia', 'US', 'SEA'),
  ('USJAX', 'Jacksonville', 'US', 'SEA'),
  ('USBOS', 'Boston', 'US', 'SEA'),
  ('USMSY', 'New Orleans', 'US', 'SEA'),
  ('USILM', 'Wilmington', 'US', 'SEA'),
  ('USGLS', 'Galveston', 'US', 'SEA'),
  ('USPDX', 'Portland', 'US', 'SEA'),
  ('USCLE', 'Cleveland', 'US', 'SEA'),
  ('CAVAN', 'Vancouver', 'CA', 'SEA'),
  ('CAMTR', 'Montreal', 'CA', 'SEA'),
  ('CAHAL', 'Halifax', 'CA', 'SEA'),
  ('CAPRR', 'Prince Rupert', 'CA', 'SEA'),
  ('CASJB', 'Saint-John', 'CA', 'SEA'),
  ('MXVER', 'Veracruz', 'MX', 'SEA'),
  ('MXZLO', 'Manzanillo', 'MX', 'SEA'),
  ('MXLZC', 'Lazaro Cardenas', 'MX', 'SEA'),
  ('MXATM', 'Altamira', 'MX', 'SEA'),
  ('MXPGO', 'Progreso', 'MX', 'SEA'),
  ('MXESE', 'Ensenada', 'MX', 'SEA'),
  ('PABLB', 'Balboa', 'PA', 'SEA'),
  ('PACTB', 'Cristobal', 'PA', 'SEA'),
  ('PAONX', 'Colon', 'PA', 'SEA'),
  ('PAMIT', 'Manzanillo', 'PA', 'SEA'),
  ('CRLIO', 'Puerto Limon', 'CR', 'SEA'),
  ('GTSTC', 'Puerto Santo Tomas de Castilla', 'GT', 'SEA'),
  ('HNPCR', 'Puerto Cortes', 'HN', 'SEA'),
  ('NICIO', 'Corinto', 'NI', 'SEA'),
  ('SVAQJ', 'Acajutla', 'SV', 'SEA'),
  ('BZBZE', 'Belize City', 'BZ', 'SEA'),
  ('DOCAU', 'Caucedo', 'DO', 'SEA'),
  ('DOHAI', 'Rio Haina', 'DO', 'SEA'),
  ('JMKIN', 'Kingston', 'JM', 'SEA'),
  ('TTPOS', 'Port-of-Spain', 'TT', 'SEA'),
  ('BSFPO', 'Freeport, Grand Bahama', 'BS', 'SEA'),
  ('BBBGI', 'Bridgetown', 'BB', 'SEA'),
  ('CWWIL', 'Willemstad', 'CW', 'SEA'),
  ('AWORJ', 'Oranjestad', 'AW', 'SEA'),
  ('BRSSZ', 'Santos', 'BR', 'SEA'),
  ('BRRIG', 'Rio Grande', 'BR', 'SEA'),
  ('BRPNG', 'Paranagua', 'BR', 'SEA'),
  ('BRRIO', 'Rio de Janeiro', 'BR', 'SEA'),
  ('BRITJ', 'Itajai', 'BR', 'SEA'),
  ('BRSUA', 'Suape Pt / Ipojuca', 'BR', 'SEA'),
  ('BRVIX', 'Vitoria', 'BR', 'SEA'),
  ('BRSSA', 'Salvador', 'BR', 'SEA'),
  ('BRFOR', 'Fortaleza', 'BR', 'SEA'),
  ('BRMAO', 'Manaus', 'BR', 'SEA'),
  ('BRIOA', 'Itapoa', 'BR', 'SEA'),
  ('ARBUE', 'Buenos Aires', 'AR', 'SEA'),
  ('ARROS', 'Rosario', 'AR', 'SEA'),
  ('CLVAP', 'Valparaiso', 'CL', 'SEA'),
  ('CLSAI', 'San Antonio', 'CL', 'SEA'),
  ('CLIQQ', 'Iquique', 'CL', 'SEA'),
  ('CLANF', 'Antofagasta', 'CL', 'SEA'),
  ('PECLL', 'Callao', 'PE', 'SEA'),
  ('PEPAI', 'Paita', 'PE', 'SEA'),
  ('COCTG', 'Cartagena', 'CO', 'SEA'),
  ('COBUN', 'Buenaventura', 'CO', 'SEA'),
  ('COBAQ', 'Barranquilla', 'CO', 'SEA'),
  ('COSMR', 'Santa Marta', 'CO', 'SEA'),
  ('ECGYE', 'Guayaquil', 'EC', 'SEA'),
  ('ECPBO', 'Puerto Bolivar', 'EC', 'SEA'),
  ('UYMVD', 'Montevideo', 'UY', 'SEA'),
  ('PYASU', 'Asuncion', 'PY', 'SEA'),
  ('VELAG', 'La Guaira', 'VE', 'SEA'),
  ('VEPBL', 'Puerto Cabello', 'VE', 'SEA'),
  ('GYGEO', 'Georgetown', 'GY', 'SEA'),
  ('SRPBM', 'Paramaribo', 'SR', 'SEA'),
  ('AUSYD', 'Sydney', 'AU', 'SEA'),
  ('AUMEL', 'Melbourne', 'AU', 'SEA'),
  ('AUBNE', 'Brisbane', 'AU', 'SEA'),
  ('AUFRE', 'Fremantle', 'AU', 'SEA'),
  ('AUADL', 'Adelaide', 'AU', 'SEA'),
  ('AUPKL', 'Port Kembla', 'AU', 'SEA'),
  ('AUDRW', 'Darwin', 'AU', 'SEA'),
  ('AUNTL', 'Newcastle', 'AU', 'SEA'),
  ('AUGLT', 'Gladstone', 'AU', 'SEA'),
  ('NZAKL', 'Auckland', 'NZ', 'SEA'),
  ('NZTRG', 'Tauranga', 'NZ', 'SEA'),
  ('NZLYT', 'Lyttelton', 'NZ', 'SEA'),
  ('NZWLG', 'Wellington', 'NZ', 'SEA'),
  ('NZNPE', 'Napier', 'NZ', 'SEA'),
  ('PGLAE', 'Lae', 'PG', 'SEA'),
  ('PGPOM', 'Port Moresby', 'PG', 'SEA'),
  ('FJSUV', 'Suva', 'FJ', 'SEA'),
  ('NCNOU', 'Noumea', 'NC', 'SEA'),
  ('PFPPT', 'Papeete', 'PF', 'SEA'),
  ('INDEL', 'Delhi', 'IN', 'AIR'),
  ('INBLR', 'Bangalore', 'IN', 'AIR'),
  ('INHYD', 'Hyderabad', 'IN', 'AIR'),
  ('INAMD', 'Ahmedabad', 'IN', 'AIR'),
  ('INTRV', 'Thiruvananthapuram (ex Trivandrum)', 'IN', 'AIR'),
  ('INGOI', 'Goa', 'IN', 'AIR'),
  ('INPNQ', 'Pune', 'IN', 'AIR'),
  ('INJAI', 'Jaipur', 'IN', 'AIR'),
  ('INLKO', 'Lucknow', 'IN', 'AIR'),
  ('INIXC', 'Chandigarh', 'IN', 'AIR'),
  ('SARUH', 'Riyadh', 'SA', 'AIR'),
  ('BHBAH', 'Bahrain International Airport', 'BH', 'AIR'),
  ('TRSAW', 'Sabiha Gokcen Apt/Istanbul', 'TR', 'AIR'),
  ('CNPVG', 'Shanghai Pudong International Apt', 'CN', 'AIR'),
  ('CNPEK', 'Beijing Shoudu International Apt', 'CN', 'AIR'),
  ('CNCAN', 'Guangzhou Baiyun International Apt', 'CN', 'AIR'),
  ('CNSZX', 'Shenzhen Baoan International Apt', 'CN', 'AIR'),
  ('CNTAO', 'Qingdao Jiaodong International Apt', 'CN', 'AIR'),
  ('CNXMN', 'Xiamen Gaoqi International Apt', 'CN', 'AIR'),
  ('KRICN', 'Incheon Intl Apt/Seoul', 'KR', 'AIR'),
  ('JPNRT', 'Narita Apt/Tokyo', 'JP', 'AIR'),
  ('JPKIX', 'Kansai Int Apt', 'JP', 'AIR'),
  ('JPHND', 'Haneda Apt/Tokyo', 'JP', 'AIR'),
  ('MYKUL', 'Kuala Lumpur', 'MY', 'AIR'),
  ('VNHAN', 'Hanoi', 'VN', 'AIR'),
  ('BDDAC', 'Dhaka', 'BD', 'AIR'),
  ('PKLHE', 'Lahore', 'PK', 'AIR'),
  ('DEFRA', 'Frankfurt am Main', 'DE', 'AIR'),
  ('DEMUC', 'Munchen', 'DE', 'AIR'),
  ('DECGN', 'Koln', 'DE', 'AIR'),
  ('BEBRU', 'Brussel (Bruxelles)', 'BE', 'AIR'),
  ('FRCDG', 'Charles-de-Gaulle Apt/Paris', 'FR', 'AIR'),
  ('FRLYS', 'Saint-Exupery Apt/Lyon', 'FR', 'AIR'),
  ('GBLHR', 'Heathrow Apt/London', 'GB', 'AIR'),
  ('GBLGW', 'Gatwick Apt/London', 'GB', 'AIR'),
  ('GBMNC', 'Manchester', 'GB', 'AIR'),
  ('ESMAD', 'Madrid', 'ES', 'AIR'),
  ('ITMXP', 'Malpensa Apt/Milano', 'IT', 'AIR'),
  ('ITFCO', 'Fiumicino', 'IT', 'AIR'),
  ('CHZRH', 'Zurich', 'CH', 'AIR'),
  ('ATVIE', 'Wien', 'AT', 'AIR'),
  ('PLWAW', 'Warszawa', 'PL', 'AIR'),
  ('CZPRG', 'Praha', 'CZ', 'AIR'),
  ('SEARN', 'Arlanda Apt/Stockholm', 'SE', 'AIR'),
  ('GRATH', 'Athinai', 'GR', 'AIR'),
  ('USJFK', 'John F. Kennedy Apt/New York', 'US', 'AIR'),
  ('USORD', 'O''Hare Apt/Chicago', 'US', 'AIR'),
  ('USATL', 'Atlanta', 'US', 'AIR'),
  ('USDFW', 'Dallas-Fort Worth Int Apt', 'US', 'AIR'),
  ('USEWR', 'Newark', 'US', 'AIR'),
  ('USSFO', 'San Francisco', 'US', 'AIR'),
  ('USIA9', 'George Bush Intercontinental Apt/Houston', 'US', 'AIR'),
  ('CAYYZ', 'Pearson International Apt/Toronto', 'CA', 'AIR'),
  ('CAYVR', 'Vancouver Apt', 'CA', 'AIR'),
  ('CAYUL', 'Montreal-Dorval Apt', 'CA', 'AIR'),
  ('MXMEX', 'Ciudad de Mexico', 'MX', 'AIR'),
  ('BRGRU', 'Guarulhos Apt / Sao Paulo', 'BR', 'AIR'),
  ('BRVCP', 'Viracopos Apt / Campinas', 'BR', 'AIR'),
  ('CLSCL', 'Santiago', 'CL', 'AIR'),
  ('COBOG', 'Bogota', 'CO', 'AIR'),
  ('PELIM', 'Lima', 'PE', 'AIR'),
  ('ZAJNB', 'Johannesburg', 'ZA', 'AIR'),
  ('KENBO', 'Nairobi', 'KE', 'AIR'),
  ('EGCAI', 'El Qahira (Cairo)', 'EG', 'AIR'),
  ('MACMN', 'Mohammed V International Airport', 'MA', 'AIR'),
  ('ETADD', 'Addis Ababa', 'ET', 'AIR'),
  ('AUPER', 'Perth', 'AU', 'AIR')
) AS v(code, name, country_code, type)
JOIN countries c ON c.code = v.country_code
ON CONFLICT (code) DO NOTHING;
