/**
 * Verifies the content of documents produced by the RUNNING API against a real
 * database, as opposed to the fixture-based check in verify-document-content.ts.
 *
 * Assertions here deliberately avoid hard-coded document numbers, because those
 * are generated by the number sequences at runtime. Instead they assert the
 * structural labels, the seeded company details, and the data this script
 * itself created through the API.
 *
 * Requires a stack that has already been exercised by verify-documents-live.ts.
 * Run: bun scripts/verify-documents-live-content.ts
 */
import fs from 'fs';
import path from 'path';
import zlib from 'zlib';

const BASE = process.env.API_BASE ?? 'http://localhost:4000/api';
const outDir = path.resolve(__dirname, '..', 'samples', 'live');

// ---------------- PDF text extraction (same approach as the fixture check) ----

function hexToText(hex: string): string {
  const clean = hex.replace(/\s+/g, '');
  let out = '';
  for (let i = 0; i + 1 < clean.length; i += 2) {
    const code = parseInt(clean.slice(i, i + 2), 16);
    if (code >= 32 && code < 255) out += String.fromCharCode(code);
  }
  return out;
}

function unescapePdf(s: string): string {
  return s
    .replace(/\\([nrtbf()\\])/g, (_, c) =>
      ({ n: '\n', r: '\r', t: '\t', b: '\b', f: '\f' } as Record<string, string>)[c] ?? c
    )
    .replace(/\\([0-7]{1,3})/g, (_, o) => String.fromCharCode(parseInt(o, 8)));
}

function extractText(buffer: Buffer): string {
  const raw = buffer.toString('latin1');
  const out: string[] = [];
  const re = /stream[\r\n]{1,2}([\s\S]*?)[\r\n]{0,2}endstream/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(raw)) !== null) {
    const chunk = Buffer.from(m[1], 'latin1');
    let text = '';
    try {
      text = zlib
        .inflateSync(chunk, { finishFlush: zlib.constants.Z_SYNC_FLUSH } as zlib.ZlibOptions)
        .toString('latin1');
    } catch {
      continue;
    }
    if (!/\bBT\b/.test(text)) continue; // skip image streams
    for (const block of text.matchAll(
      /\[((?:[^\][]|\\.)*)\]\s*TJ|\((?:\\.|[^()\\])*\)\s*Tj|<([0-9A-Fa-f\s]+)>\s*Tj/g
    )) {
      let run = '';
      for (const t of block[0].matchAll(/\(((?:\\.|[^()\\])*)\)/g)) run += unescapePdf(t[1]);
      for (const h of block[0].matchAll(/<([0-9A-Fa-f\s]+)>/g)) run += hexToText(h[1]);
      if (run) out.push(run);
    }
  }
  return out.join(' ').replace(/\s+/g, ' ');
}

// ---------------- drive the API ----------------------------------------------

let token = '';
let passes = 0;
let failures = 0;

function check(name: string, ok: boolean, detail = '') {
  if (ok) {
    passes++;
    console.log(`  PASS  ${name}`);
  } else {
    failures++;
    console.log(`  FAIL  ${name}${detail ? ' -> ' + detail : ''}`);
  }
}

async function get(pathname: string): Promise<any> {
  const res = await fetch(`${BASE}${pathname}`, { headers: { Authorization: `Bearer ${token}` } });
  return res.json();
}

async function getPdf(pathname: string): Promise<Buffer> {
  const res = await fetch(`${BASE}${pathname}`, { headers: { Authorization: `Bearer ${token}` } });
  return Buffer.from(await res.arrayBuffer());
}

async function main() {
  const login = await fetch(`${BASE}/auth/login`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ email: 'founder@seabridge.com', password: process.env.SEED_FOUNDER_PASSWORD ?? 'admin123' }),
  });
  token = (await login.json()).data.token;
  if (!token) {
    console.log('could not authenticate');
    process.exit(1);
  }

  fs.mkdirSync(outDir, { recursive: true });

  const quotations = await get('/quotations');
  const orders = await get('/orders');
  const invoices = await get('/invoices');

  const quotation = quotations.data?.[0];
  const order = orders.data?.[0];
  if (!quotation || !order) {
    console.log('no quotation/order present - run verify-documents-live.ts first');
    process.exit(1);
  }

  // Company details come from the seeded profile, so they must appear on all.
  const companyFields = ['VISION LIMELITE', 'Ahmedabad', 'info@seabridgeexports.com'];

  // ---- Quotation ----
  {
    const buf = await getPdf(`/quotations/${quotation.id}/pdf`);
    fs.writeFileSync(path.join(outDir, 'Quotation.pdf'), buf);
    const text = extractText(buf);
    console.log(`\n=== Quotation (${quotation.quotationNumber}) ===`);
    for (const f of companyFields) check(`company: ${f}`, text.includes(f));
    check('title', text.includes('QUOTATION'));
    check('its own quotation number', text.includes(quotation.quotationNumber));
    check('buyer name', text.includes('MartinoRossi'));
    check('column headers', text.includes('Product Code') && text.includes('Unit Type'));
    check('HS code of the seeded product', text.includes('12119032'));
    check('terms block', text.includes('jurisdiction'));
    check('amount in words', /USD [A-Z ]+ONLY/.test(text));
    check('no bank details on a quotation', !text.includes('Bank Details'));
  }

  // ---- Packing List ----
  {
    const buf = await getPdf(`/orders/${order.id}/packing-list`);
    fs.writeFileSync(path.join(outDir, 'PackingList.pdf'), buf);
    const text = extractText(buf);
    console.log(`\n=== Packing List (${order.orderNumber}) ===`);
    check('title', text.includes('PACKING LIST'));
    check('its own order number', text.includes(order.orderNumber));
    check('packing columns', text.includes('No. of Packages') && text.includes('Bag / Carton Per KGs'));
    check('weight columns', text.includes('Net Weight') && text.includes('Gross Weight'));
    check('totals row', text.includes('TOTAL NET WEIGHT') && text.includes('TOTAL GROSS WEIGHT'));
    check('recorded net weight 500', text.includes('500'));
    check('recorded gross weight 520', text.includes('520'));
    check('dispatch method from the order', text.includes('Sea'));
    check('shipment type from the order', text.includes('FCL'));
    check('country of origin', text.includes('India'));
    check('no prices on a packing list', !text.includes('Amount in words') && !text.includes('11.80'));
  }

  // ---- the three invoice types ----
  for (const inv of invoices.data ?? []) {
    const label =
      inv.type === 'PROFORMA' ? 'ProformaInvoice' : inv.type === 'SAMPLE' ? 'SampleInvoice' : 'CommercialInvoice';
    const buf = await getPdf(`/invoices/${inv.id}/pdf`);
    fs.writeFileSync(path.join(outDir, `${label}.pdf`), buf);
    const text = extractText(buf);

    console.log(`\n=== ${label} (${inv.invoiceNumber}, type ${inv.type}) ===`);
    for (const f of companyFields) check(`company: ${f}`, text.includes(f));
    check('GST number', text.includes('24DUBPP8360J1ZB'));
    check('its own invoice number', text.includes(inv.invoiceNumber));
    check('buyer order reference', text.includes('PO-8891'));
    check('HS code column', text.includes('HS Code'));
    check('dispatch header fields', text.includes('Method Of Dispatch') && text.includes('Port Of Loading'));
    check('amount in words', /USD [A-Z ]+ONLY/.test(text));
    check('packing summary from the order', text.includes('Total Cartons / Box'));

    const expectedTitle =
      inv.type === 'PROFORMA' ? 'PROFORMA INVOICE' : inv.type === 'SAMPLE' ? 'SAMPLE INVOICE' : 'COMMERCIAL INVOICE';
    check(`correct template title: ${expectedTitle}`, text.includes(expectedTitle));

    if (inv.type === 'SAMPLE') {
      check('sample carries NOT FOR SALE', text.includes('NOT FOR SALE'));
      check('sample states non-hazardous', text.includes('non-hazardous'));
      check('sample omits bank details', !text.includes('KKBKINBBXX'));
      check('sample uses Unit Rate heading', text.includes('Unit Rate'));
    } else {
      check('bank details present', text.includes('Bank Details') && text.includes('KKBKINBBXX'));
      check('IFSC present', text.includes('KKBK0002576'));
      check('banking charges note', text.includes('BANKING CHARGES OUTSIDE INDIA'));
      check('declaration present', text.includes('actual Price of goods'));
      // Regression: terms used to be blank when the invoice carried none of its
      // own; they should now fall back to the order's payment terms.
      check('payment terms fall back to the order', text.includes('40% Advance'));
      check('not flagged NOT FOR SALE', !text.includes('NOT FOR SALE'));
      check('variation percent shown', text.includes('Variation'));
    }
  }

  console.log(`\n${'-'.repeat(60)}`);
  console.log(`${passes} passed, ${failures} failed`);
  process.exit(failures === 0 ? 0 : 1);
}

main().catch((e) => {
  console.error('unexpected error:', e);
  process.exit(1);
});
